/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CharacterHistorySchema extends BaseModel {
  static $columns = [
    'characterId',
    'createdAt',
    'deletedAt',
    'historyTypeId',
    'id',
    'payload',
    'updatedAt',
  ] as const
  $columns = CharacterHistorySchema.$columns
  @column()
  declare characterId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare historyTypeId: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare payload: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CharacterSchema extends BaseModel {
  static $columns = [
    'bossesKilled',
    'createdAt',
    'currency',
    'deaths',
    'deletedAt',
    'duelsWon',
    'enemiesKilled',
    'entityPropertyId',
    'experience',
    'id',
    'inventorySize',
    'level',
    'luckyCharm',
    'name',
    'secretsItemsFound',
    'totalDuels',
    'totalExperience',
    'updatedAt',
    'userId',
  ] as const
  $columns = CharacterSchema.$columns
  @column()
  declare bossesKilled: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: number
  @column()
  declare deaths: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare duelsWon: number
  @column()
  declare enemiesKilled: number
  @column()
  declare entityPropertyId: string | null
  @column()
  declare experience: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inventorySize: number
  @column()
  declare level: number
  @column.dateTime()
  declare luckyCharm: DateTime | null
  @column()
  declare name: string
  @column()
  declare secretsItemsFound: number
  @column()
  declare totalDuels: number
  @column()
  declare totalExperience: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class DifficultySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = DifficultySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EnemySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'description',
    'entityPropertyId',
    'id',
    'isBoss',
    'name',
    'updatedAt',
  ] as const
  $columns = EnemySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare entityPropertyId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isBoss: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EnemyTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = EnemyTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EnemyWorldSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'enemyId',
    'id',
    'isActive',
    'updatedAt',
    'worldId',
  ] as const
  $columns = EnemyWorldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare enemyId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare worldId: string | null
}

export class EntitySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = EntitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EntityPropertySchema extends BaseModel {
  static $columns = [
    'charisma',
    'constitution',
    'createdAt',
    'deletedAt',
    'dexterity',
    'entityId',
    'entityType',
    'id',
    'intelligence',
    'luck',
    'perception',
    'strength',
    'updatedAt',
    'wisdom',
  ] as const
  $columns = EntityPropertySchema.$columns
  @column()
  declare charisma: number
  @column()
  declare constitution: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare dexterity: number
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare intelligence: number
  @column()
  declare luck: number
  @column()
  declare perception: number
  @column()
  declare strength: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wisdom: number
}

export class EventWorldSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'eventId',
    'id',
    'isActive',
    'updatedAt',
    'worldId',
  ] as const
  $columns = EventWorldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare eventId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare worldId: string | null
}

export class EventSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'description',
    'difficultyId',
    'end',
    'id',
    'limitAmount',
    'limitId',
    'name',
    'start',
    'updatedAt',
  ] as const
  $columns = EventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare difficultyId: number | null
  @column.dateTime()
  declare end: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare limitAmount: number
  @column()
  declare limitId: number | null
  @column()
  declare name: string
  @column.dateTime()
  declare start: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HistoryTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = HistoryTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InventoryItemSchema extends BaseModel {
  static $columns = [
    'characterId',
    'createdAt',
    'deletedAt',
    'hasSuffix',
    'id',
    'isEquipped',
    'itemId',
    'itemSuffixId',
    'page',
    'position',
    'quantity',
    'updatedAt',
  ] as const
  $columns = InventoryItemSchema.$columns
  @column()
  declare characterId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare hasSuffix: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEquipped: boolean | null
  @column()
  declare itemId: string | null
  @column()
  declare itemSuffixId: string | null
  @column()
  declare page: number | null
  @column()
  declare position: any | null
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemBaseSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'description',
    'entityPropertyId',
    'id',
    'image',
    'itemCategoryId',
    'name',
    'updatedAt',
  ] as const
  $columns = ItemBaseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare entityPropertyId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare itemCategoryId: number | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemCategorySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'id',
    'inventorySpaceHeight',
    'inventorySpaceWidth',
    'isEquippable',
    'isStackable',
    'isUsable',
    'name',
    'updatedAt',
  ] as const
  $columns = ItemCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inventorySpaceHeight: number
  @column()
  declare inventorySpaceWidth: number
  @column()
  declare isEquippable: boolean | null
  @column()
  declare isStackable: boolean | null
  @column()
  declare isUsable: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemItemListSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'dropChance',
    'id',
    'itemId',
    'itemListId',
    'onlyBoss',
    'updatedAt',
  ] as const
  $columns = ItemItemListSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare dropChance: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itemId: string | null
  @column()
  declare itemListId: string | null
  @column()
  declare onlyBoss: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemListWorldSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'id',
    'isActive',
    'itemListId',
    'updatedAt',
    'worldId',
  ] as const
  $columns = ItemListWorldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare itemListId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare worldId: string | null
}

export class ItemListSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = ItemListSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemPropertySchema extends BaseModel {
  static $columns = [
    'calculationType',
    'createdAt',
    'deletedAt',
    'duration',
    'entityId',
    'entityType',
    'id',
    'propertyType',
    'updatedAt',
    'value',
  ] as const
  $columns = ItemPropertySchema.$columns
  @column()
  declare calculationType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare duration: number
  @column()
  declare entityId: string
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare propertyType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: number
}

export class ItemRaritySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = ItemRaritySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemSuffixSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = ItemSuffixSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemWorldSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'dropChance',
    'id',
    'itemId',
    'onlyBoss',
    'updatedAt',
    'worldId',
  ] as const
  $columns = ItemWorldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare dropChance: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itemId: string | null
  @column()
  declare onlyBoss: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare worldId: string | null
}

export class ItemSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'description',
    'id',
    'image',
    'isActive',
    'isTradeable',
    'itemBaseId',
    'itemRarityId',
    'level',
    'name',
    'updatedAt',
  ] as const
  $columns = ItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare isTradeable: boolean | null
  @column()
  declare itemBaseId: string | null
  @column()
  declare itemRarityId: number | null
  @column()
  declare level: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LimitSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = LimitSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'email',
    'id',
    'lastLoginAt',
    'lastSessionId',
    'password',
    'rememberMeToken',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare lastSessionId: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare rememberMeToken: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class WorldSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'description',
    'difficultyId',
    'id',
    'image',
    'isActive',
    'maxDrop',
    'name',
    'requirements',
    'updatedAt',
  ] as const
  $columns = WorldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare difficultyId: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare maxDrop: number
  @column()
  declare name: string
  @column()
  declare requirements: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
